version: '3.9'

services:
  frontend:
    # network_mode: host
    build: ./frontend
    ports: ["5173:5173"]  
    depends_on:
      - ganache
  backend:
    # network_mode: host
    build: ./backend
    ports: ["8000:8000"]  
    depends_on:
      - db
      - ganache
  ganache:
    # network_mode: host
    build: ./smart_contract
    ports: ["8545:8545"]
  db:
    # network_mode: host
    volumes:
      - app_db:/data/db
    image: mongo:latest
    ports: ["27017:27017"] 
volumes:
  app_db: